#if defined(SIMU)
    #define CONF_GUI_SCREEN_WIDTH  240
    #define CONF_GUI_SCREEN_HEIGHT 240

    #define CONF_GUI_DATA_SCREEN_TEMPERATURE_AVAILABLE 1
    #if CONF_GUI_DATA_SCREEN_TEMPERATURE_AVAILABLE
        #define CONF_GUI_DATA_SCREEN_TEMPERATURE_ORDER 0
    #endif

    #define CONF_GUI_DATA_SCREEN_HUMIDITY_AVAILABLE 1
    #if CONF_GUI_DATA_SCREEN_HUMIDITY_AVAILABLE
        #define CONF_GUI_DATA_SCREEN_HUMIDITY_ORDER 1
    #endif

    #define CONF_GUI_DATA_SCREEN_PRESSURE_AVAILABLE 1
    #if CONF_GUI_DATA_SCREEN_PRESSURE_AVAILABLE
        #define CONF_GUI_DATA_SCREEN_PRESSURE_ORDER 2
    #endif

    #define CONF_GUI_DATA_SCREEN_AIR_QUALITY_AVAILABLE 1
    #if CONF_GUI_DATA_SCREEN_AIR_QUALITY_AVAILABLE
        #define CONF_GUI_DATA_SCREEN_AIR_QUALITY_ORDER 3
    #endif
#endif
