#ifndef GUI_CONF_INTERNAL_H
#ifdef __has_include
    #if __has_include("gui_conf.h")
        #include "gui_conf.h"
    #else
        #error "gui_conf.h is missing"
    #endif
#endif
#endif  /*GUI_CONF_INTERNAL_H*/


#ifdef CONF_GUI_SCREEN_WIDTH
    #define GUI_SCREEN_WIDTH CONF_GUI_SCREEN_WIDTH
#else
    #error "gui_conf.h: CONF_GUI_SCREEN_WIDTH is missing"
#endif


#ifdef CONF_GUI_SCREEN_HEIGHT
    #define GUI_SCREEN_HEIGHT CONF_GUI_SCREEN_HEIGHT
#else
    #error "gui_conf.h: CONF_GUI_SCREEN_HEIGHT is missing"
#endif

#define GUI_DATA_SCREEN_TEMPERATURE_AVAILABLE CONF_GUI_DATA_SCREEN_TEMPERATURE_AVAILABLE
#if GUI_DATA_SCREEN_TEMPERATURE_AVAILABLE
    #ifdef CONF_GUI_DATA_SCREEN_TEMPERATURE_ORDER
        #define GUI_DATA_SCREEN_TEMPERATURE_ORDER CONF_GUI_DATA_SCREEN_TEMPERATURE_ORDER
    #else
        #error "gui_conf.h: 'CONF_GUI_DATA_SCREEN_TEMPERATURE_AVAILABLE' enable but 'CONF_GUI_DATA_SCREEN_TEMPERATURE_ORDER' is missing"
    #endif
#endif

#define GUI_DATA_SCREEN_HUMIDITY_AVAILABLE CONF_GUI_DATA_SCREEN_HUMIDITY_AVAILABLE
#define GUI_DATA_SCREEN_HUMIDITY_ORDER -100
#if GUI_DATA_SCREEN_HUMIDITY_AVAILABLE
    #ifdef CONF_GUI_DATA_SCREEN_HUMIDITY_ORDER
        #define GUI_DATA_SCREEN_HUMIDITY_ORDER CONF_GUI_DATA_SCREEN_HUMIDITY_ORDER
    #else
        #error "gui_conf.h: 'CONF_GUI_DATA_SCREEN_HUMIDITY_AVAILABLE' enable but 'CONF_GUI_DATA_SCREEN_HUMIDITY_ORDER' is missing"
    #endif
#endif

#define GUI_DATA_SCREEN_PRESSURE_AVAILABLE CONF_GUI_DATA_SCREEN_PRESSURE_AVAILABLE
#if GUI_DATA_SCREEN_PRESSURE_AVAILABLE
    #ifdef CONF_GUI_DATA_SCREEN_PRESSURE_ORDER
        #define GUI_DATA_SCREEN_PRESSURE_ORDER CONF_GUI_DATA_SCREEN_PRESSURE_ORDER
    #else
        #error "gui_conf.h: 'CONF_GUI_DATA_SCREEN_PRESSURE_AVAILABLE' enable but 'CONF_GUI_DATA_SCREEN_PRESSURE_ORDER' is missing"
    #endif
#endif

#define GUI_DATA_SCREEN_AIR_QUALITY_AVAILABLE CONF_GUI_DATA_SCREEN_AIR_QUALITY_AVAILABLE
#if GUI_DATA_SCREEN_AIR_QUALITY_AVAILABLE
    #ifdef CONF_GUI_DATA_SCREEN_AIR_QUALITY_ORDER
        #define GUI_DATA_SCREEN_AIR_QUALITY_ORDER CONF_GUI_DATA_SCREEN_AIR_QUALITY_ORDER
    #else
        #error "gui_conf.h: 'CONF_GUI_DATA_SCREEN_AIR_QUALITY_AVAILABLE' enable but 'CONF_GUI_DATA_SCREEN_AIR_QUALITY_ORDER' is missing"
    #endif
#endif